# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZhiHuFans_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZhiHuFans_iOS
  pod 'Ono'
  pod 'QMUIKit', '~>1.3.1'

end
