# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhiHuFans_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZhiHuFans_iOS

  pod 'Ono'

  target 'ZhiHuFans_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
